# Generated by Django 5.0.3 on 2024-03-28 08:22

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=user.models.CaseInsensitiveEmailField(max_length=254, unique=True),
        ),
    ]
